### ISSUE TITLE
Getting Onpost route error while exporting and looks good for onGet

### ISSUE THREAD

**Issue by badrinath389** [hapinessjs/swag-module#15]
![image](https://user-images.githubusercontent.com/25297997/38926066-077291da-431f-11e8-9d94-0e935342fff4.png)
Can you please provide what are the properties needs to be imported

`Property 'onGet' is missing in type 'GetHtmlUniversalRoute'.`

```
import {OnPost, Request, Route, ReplyNoContinue, OnPostHandler, HTTPHandlerResponse} from '@hapiness/core';

@Route({
    path: '/api/demoEmail',
    method: 'GET'
})
export class GetHtmlUniversalRoute implements OnPost {
    OnPost(request: Request, reply: ReplyNoContinue) {
        reply({
            message : 'Text Message'
        });
    }
}
```

**Comment by srz09** [comment]
Hi,
In fact there is some errors in your code.
I suppose you are created a route called ```GetHtmlUniversalRoute``` ?
If yes, see errors above:
1/ you are writing that the route is a ```GET``` but you want to implements OnPost instead of OnGet
2/ if you implements, ```OnPost```, or ```OnGet```, the function inside your class, the functions you should override are respectively ```onPost(req, reply) { /* ... */ }```, ```onGet(req, reply) { /* ... */}``` etc.
If your problem does concerned the hapiness framework and not directly the swag module, the next time you can open an issue on the ```core``` project of hapiness.
Hope it helps!
Cheers
